import os
import json
import requests
from datetime import datetime
from langchain.tools import tool
from pydantic import BaseModel, Field
from src.config import GITHUB_TOKEN, GITHUB_REPO

TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "..", "templates", "ticket.html")

class TicketSchema(BaseModel):
    name: str = Field(description="The name of the user creating the ticket")
    email: str = Field(description="The contact email of the user")
    summary: str = Field(description="A brief summary or title of the issue")
    description: str = Field(description="A detailed description of the problem")

def _render_html(ticket_id: int, name: str, email: str, summary: str,
                 description: str, status: str, created_at: str, github_url: str) -> str:
    try:
        with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
            html = f.read()
    except FileNotFoundError:
        return ""

    status_class = "open" if status.lower() == "open" else "closed"

    html = html.replace("{{ticket_id}}", str(ticket_id))
    html = html.replace("{{name}}", name)
    html = html.replace("{{email}}", email)
    html = html.replace("{{summary}}", summary)
    html = html.replace("{{description}}", description)
    html = html.replace("{{status}}", status)
    html = html.replace("{{status_class}}", status_class)
    html = html.replace("{{created_at}}", created_at)

    if github_url:
        block_start = html.find("{{#if github_url}}")
        block_end = html.find("{{/if}}")
        if block_start != -1 and block_end != -1:
            inner = html[block_start + len("{{#if github_url}}"):block_end]
            inner = inner.replace("{{github_url}}", github_url)
            html = html[:block_start] + inner + html[block_end + len("{{/if}}"):]
    else:
        import re
        html = re.sub(r"\{\{#if github_url\}\}.*?\{\{/if\}\}", "", html, flags=re.DOTALL)

    return html

def _github_issue_body(ticket_id: int, name: str, email: str,
                       summary: str, description: str, created_at: str) -> str:
    return f"""## Support Ticket #{ticket_id}

| Field | Value |
|-------|-------|
| **Name** | {name} |
| **Email** | {email} |
| **Created** | {created_at} |
| **Status** | 🟢 Open |

---

### Description

{description}

---

*This ticket was automatically generated by AstroCorp Universal Knowledge Assistant.*
*Contact: support@astrocorp.uz | +998 71 123 45 67*
"""

@tool("create_support_ticket", args_schema=TicketSchema)
def create_support_ticket(name: str, email: str, summary: str, description: str) -> str:
    """
    Creates a support ticket in the issue tracking system (GitHub Issues).
    Use this when a user needs further assistance or when information is not found in documents.
    """
    os.makedirs("tickets", exist_ok=True)
    ticket_id = len(os.listdir("tickets")) + 1
    created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    github_url = ""
    github_status = ""

    if GITHUB_TOKEN:
        try:
            url = f"https://api.github.com/repos/{GITHUB_REPO}/issues"
            headers = {
                "Authorization": f"token {GITHUB_TOKEN}",
                "Accept": "application/vnd.github.v3+json"
            }
            payload = {
                "title": f"[TICKET #{ticket_id}] {summary}",
                "body": _github_issue_body(ticket_id, name, email, summary, description, created_at),
                "labels": ["support", "customer-ticket"]
            }
            response = requests.post(url, json=payload, headers=headers)
            if response.status_code == 201:
                github_url = response.json().get("html_url", "")
                github_status = f" GitHub Issue: {github_url}"
            else:
                github_status = f" (GitHub sync failed: {response.status_code})"
        except Exception as e:
            github_status = f" (GitHub error: {str(e)})"
    else:
        github_status = " (Note: GitHub sync skipped — GITHUB_TOKEN not set)"

    ticket_data = {
        "id": ticket_id,
        "name": name,
        "email": email,
        "summary": summary,
        "description": description,
        "status": "Open",
        "created_at": created_at,
        "github_url": github_url
    }

    json_path = f"tickets/ticket_{ticket_id}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(ticket_data, f, indent=4, ensure_ascii=False)

    html = _render_html(ticket_id, name, email, summary, description,
                        "Open", created_at, github_url)
    if html:
        html_path = f"tickets/ticket_{ticket_id}.html"
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)

    return (
        f"Success! Ticket #{ticket_id} has been created for {name}.{github_status} "
        f"Our team will contact you at {email} shortly."
    )

tools = [create_support_ticket]
